### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5

### ISSUE THREAD

**Issue by Ryan0lb** [n00dles/ogma-CMS#40]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Discovered by: Ryan0lb

details:
Open this url “http://127.0.0.1/admin/“ and login in
view the "Pages" and Edit 404 Pages
![图片](https://user-images.githubusercontent.com/15329046/54367497-6c31cb80-46ad-11e9-945d-96a62aa913f6.png)
Insert the payload:"<script>alert("test")</script>" in Content
![图片](https://user-images.githubusercontent.com/15329046/54368016-54a71280-46ae-11e9-8c82-8aa9e0895856.png)
finally,save changes!
The malicious javascript payload executed for it successlly
![图片](https://user-images.githubusercontent.com/15329046/54368483-35f54b80-46af-11e9-8139-4839036aeb0a.png)
Then we can go to any 404 pages,for example:1.php/2.php
![图片](https://user-images.githubusercontent.com/15329046/54368699-984e4c00-46af-11e9-8812-ac5d92492e30.png)
![图片](https://user-images.githubusercontent.com/15329046/54368756-ac924900-46af-11e9-8393-26f9e34707f0.png)
Without any filtering on 404 pages, we can easily trigger malicious XSS Payload and attack every visitor maliciously.

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
