### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5 http://127.0.0.1/ceshi2/admin/pages.php?action=edit

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#41]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：Create New Page - Page Title title has XSS(Stored)
payload："><script>alert(1);</script>aaaa

#### Create a new page
![image](https://user-images.githubusercontent.com/30485210/65300652-d66c8100-dba6-11e9-8404-a43f890e59c1.png)
#### Enter payload in the title of the page
![image](https://user-images.githubusercontent.com/30485210/65300678-edab6e80-dba6-11e9-9983-211a3b9ad244.png)
#### save
![image](https://user-images.githubusercontent.com/30485210/65300714-13d10e80-dba7-11e9-8079-11f6367b893c.png)
#### click edit
![image](https://user-images.githubusercontent.com/30485210/65300814-57c41380-dba7-11e9-9acd-3932648f7575.png)
#### Success
![image](https://user-images.githubusercontent.com/30485210/65300866-9a85eb80-dba7-11e9-9357-b17148ca69e2.png)

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
