### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5  View Blogs  Create New Blog Post

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#42]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：View Blogs  Create-New Blog Posthas XSS(Stored)
payload："><script>alert(1);</script>aaaa

#### click Create New Blog Post
![image](https://user-images.githubusercontent.com/30485210/65301377-cace8980-dba9-11e9-898f-afee7a9f6172.png)
#### Enter payload in the title of the page
![image](https://user-images.githubusercontent.com/30485210/65301423-01a49f80-dbaa-11e9-8da7-a51ef95f7638.png)
#### save
![image](https://user-images.githubusercontent.com/30485210/65301427-0a957100-dbaa-11e9-8613-f3ce38c9016d.png)
#### Access page：http://127.0.0.1/ceshi2/blog
![image](https://user-images.githubusercontent.com/30485210/65301762-54cb2200-dbab-11e9-9569-7f2f7dc8a5b2.png)

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
