### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5 Blog-Content content field

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#43]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：Blog-Content content field has XSS(Stored)
payload："><script>alert(1);</script>aaaa

#### click Edit
![image](https://user-images.githubusercontent.com/30485210/65302377-9ceb4400-dbad-11e9-9d19-236f5172e7f6.png)
#### Enter payload
![image](https://user-images.githubusercontent.com/30485210/65302405-b12f4100-dbad-11e9-988c-edcd3ba8207f.png)
#### save
![image](https://user-images.githubusercontent.com/30485210/65302417-ba201280-dbad-11e9-8f48-1f3da460a88a.png)
#### Access page：http://127.0.0.1/ceshi2/blog
![image](https://user-images.githubusercontent.com/30485210/65303027-5e568900-dbaf-11e9-931c-2b6c5affca7e.png)
#### Success

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
