### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5 Edit Menu: main-Label

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#44]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：Edit Menu: main-Label field has XSS(Stored)
payload："><script>alert(1);</script>aaaa

### Enter payload
![image](https://user-images.githubusercontent.com/30485210/65565909-f1166f80-df83-11e9-8283-10cacb4f33a9.png)
### Click Add
![image](https://user-images.githubusercontent.com/30485210/65565929-fbd10480-df83-11e9-961c-de8fdbaaa077.png)
### Success
![image](https://user-images.githubusercontent.com/30485210/65565948-05f30300-df84-11e9-9c95-68f5798a0c0d.png)

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
