### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5 View Media-Create New Media-tag field

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#45]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：View Media-Create New Media-tag field
payload："><script>alert(1);</script>aaaa
### click Create
![image](https://user-images.githubusercontent.com/30485210/65566303-f2946780-df84-11e9-901c-456b8c73535d.png)
### enter payload
![image](https://user-images.githubusercontent.com/30485210/65566378-35eed600-df85-11e9-9c8c-dbf9a4d93744.png)
### success
![image](https://user-images.githubusercontent.com/30485210/65566482-9120c880-df85-11e9-993f-4cf83cc93048.png)

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
