### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5 View Media-Create New Media-title field 

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#46]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：View Media-Create New Media-title field
payload："><script>alert(1);</script>aaaa
### click Create
![image](https://user-images.githubusercontent.com/30485210/65566303-f2946780-df84-11e9-901c-456b8c73535d.png)
### enter payload
![image](https://user-images.githubusercontent.com/30485210/65566598-f674b980-df85-11e9-838b-9db807b60644.png)
### click edit
![image](https://user-images.githubusercontent.com/30485210/65566623-055b6c00-df86-11e9-8636-6e0c4365232c.png)
### success
![image](https://user-images.githubusercontent.com/30485210/65566590-eeb51500-df85-11e9-883e-f464f912009b.png)

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code.
I no longer support or will update this version on github.
