### ISSUE TITLE
XSS(Stored) in ogma-CMS_v0.5 Edit User-Username

### ISSUE THREAD

**Issue by HLHai** [n00dles/ogma-CMS#47]
Affected software:ogma-CMS_v0.5
Type of vulnerability: XSS (Stored)
Explain：Edit Menu:  Edit User-Username has XSS(Stored)
payload："><script>alert(1);</script>aaaa
### click edit 
![image](https://user-images.githubusercontent.com/30485210/65567202-e65dd980-df87-11e9-9980-1e7334274d96.png)
### enter payload
![image](https://user-images.githubusercontent.com/30485210/65567217-fc6b9a00-df87-11e9-92ab-a0dc942b6f5d.png)
### save
![image](https://user-images.githubusercontent.com/30485210/65567221-04c3d500-df88-11e9-8001-4904a36da720.png)
### success
![image](https://user-images.githubusercontent.com/30485210/65567237-0d1c1000-df88-11e9-8ae5-4bb0cc309403.png)

**Comment by n00dles** [comment]
This has been resolved in an unreleased version of the code. 
I no longer support or will update this version on github.
